version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SENDER_EMAIL=${SENDER_EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}