# Generated by Django 6.0.3 on 2026-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
