# Generated by Django 6.0.3 on 2026-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigncontact_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigncontact',
            old_name='email',
            new_name='recipient',
        ),
    ]
